### ISSUE TITLE
ToDo: Write unit tests + travis-ci integration

### ISSUE THREAD

**Issue by anx-ckreuzberger** [anx-ckreuzberger/django-request-cache#3]
- [ ] Write unit tests that verify that within a single request an annotated method is only called once
- [ ] Add tox.ini file with tests, like [here](https://github.com/anx-ckreuzberger/django-rest-multiauthtoken/blob/master/tox.ini) to test this package against multiple Python and Django Versions
- [ ] Add travis-ci integration, like [here](https://github.com/anx-ckreuzberger/django-rest-multiauthtoken/blob/master/.travis.yml)
- [ ] Add travis-ci and pypi badges to the README
